<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>$(TargetFramework)</TargetFramework>
        <OutputType>Library</OutputType>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="MonoGame.Framework.DesktopGL" Version="$(MonoGameFrameworkDesktopGLVersion)" />
  <PackageReference Include="MonoGame.Content.Builder.Task" Version="$(MonoGameContentBuilderTaskVersion)" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Enginus.Core\Enginus.Core.csproj" />
	</ItemGroup>
</Project>